### ISSUE TITLE
Complete Works?

### ISSUE THREAD

**Issue by eggsyntax** [georgjaehnig/webpages-to-ebook#10]
Hey! Thanks so much for doing this for SSC. If it's easy for you to do with your current setup, would you be willing to create a single epub with all of them, ie _The Complete Works of Scott Alexander_? Totally fine if you don't have time, but it'd be a great thing to have :)

**Comment by benide** [comment]
I just finished putting together a YAML file for that and was going to open an issue to see if @georgjaehnig wanted it, but I guess I don't need to open an issue now!

I took the html source from [this link](https://web.archive.org/web/20200618075053/https://slatestarcodex.com/archives/), named it `ssc-source`, then ran the following in bash:
```bash
grep -oP '(?<=")(https://web.archive.org/web/20200618075053/https://slatestarcodex.com/[\d]+/[\d]+/[\d]+/[^"]++)(?=")' ssc-source | grep -vP '(/open-thread)|(/ot)|(meetup)|(classified)' | sort | uniq | awk '{ print "- " $0 }' > ssc-archive.yml 
```
then edited from that to create [this yaml file](https://gist.github.com/benide/a3c159f2fa541e8a040910dcd84af34b). I haven't actually tried running this yet.

Note: I removed open threads, classifieds, and meetups. Also, I'm sure there is a much prettier way to get the same result, but I'm working with limited command line knowledge :)


edit: I accidentally didn't do it with the latest version of the archive. That's fixed now.

**Comment by georgjaehnig** [comment]
Thanks, @benide! Got your file and running the script now... :)

**Comment by georgjaehnig** [comment]
@benide So the script ran but some URLs threw 404. Here's a list of them (not exhaustive, there are more from older years):

- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2016/08/25/devoodooifying-psychology/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2016/08/31/terrorists-vs-chairs-an-outlier-story/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2016/09/12/its-bayes-all-the-way-up/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2016/10/13/more-hardball-debate-questions/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2016/12/12/might-people-on-the-internet-sometimes-lie/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2017/01/17/another-followup-to-economists-on-education/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2017/01/18/watch-new-health-picks/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2017/02/22/repost-the-non-libertarian-faq/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2017/03/16/book-review-seeing-like-a-state/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2017/03/17/ssc-survey-2017-results/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2017/03/24/guided-by-the-beauty-of-our-weapons/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2017/03/30/links-317-relinkquishment/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2017/04/07/yes-we-have-noticed-the-skulls/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2017/04/11/sacred-principles-as-exhaustible-resources/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2017/04/13/chametz/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2017/04/25/book-review-the-hungry-brain/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2017/05/30/hungarian-education-iii-mastering-the-core-teachings-of-the-budapestians/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2017/06/21/against-murderism/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2017/06/26/conversation-deliberately-skirts-the-border-of-incomprehensibility/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2017/07/14/can-we-link-perception-and-cognition/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2017/07/24/targeting-meritocracy/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2017/07/26/dont-blame-griggs/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2017/07/29/against-signal-boosting-as-doxxing/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2017/08/02/where-the-falling-einstein-meets-the-rising-mouse/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2017/08/28/contra-askell-on-moral-offsets/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2017/08/29/my-irb-nightmare/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2017/09/05/book-review-surfing-uncertainty/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2017/09/27/against-individual-iq-worries/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2017/10/23/kolmogorov-complicity-and-the-parable-of-lightning/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2017/10/25/against-rat-park/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2017/12/28/adderall-risks-much-more-than-you-wanted-to-know/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2018/01/24/conflict-vs-mistake/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2018/02/13/weve-got-five-years-what-a-surprise/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2018/03/08/ssc-journal-club-friston-on-computational-mood/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2018/04/26/call-for-adversarial-collaborations/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2018/04/30/book-review-history-of-the-fabian-society/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2018/05/08/varieties-of-argumentative-experience/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2018/06/24/book-review-capital-in-the-twenty-first-century/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2018/07/05/the-craft-and-the-codex/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2018/07/10/melatonin-much-more-than-you-wanted-to-know/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2018/07/18/the-whole-city-is-center/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2018/08/06/before-you-get-too-excited-about-that-trigger-warning-study/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2018/08/28/links-8-18-urlin-wall/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2018/10/08/links-10-18-1-insiteful/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2018/11/07/ssris-an-update/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2019/01/13/ssc-survey-results-2019/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2019/01/14/too-many-people-dare-call-it-conspiracy/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2019/01/15/kernel-of-doubt-testing-math-preference-vs-corn-eating-style/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2019/02/22/rip-culture-war-thread/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2019/02/26/rule-genius-in-not-out/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2019/03/06/links-3-19-linkguini/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2019/04/22/1960-the-year-the-singularity-was-cancelled/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2019/06/03/repost-epistemic-learned-helplessness/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2019/06/10/book-review-the-prices-are-too-dmn-high/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2019/09/02/book-review-ages-of-discord/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2019/09/10/ssc-journal-club-relaxed-beliefs-under-psychedelics-and-the-anarchic-brain/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2019/10/07/links-10-19/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2019/10/21/the-pnse-paper/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2019/11/13/autism-and-intelligence-much-more-than-you-wanted-to-know/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2019/12/04/symptom-condition-cause/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2020/01/13/2019-adversarial-collaboration-winners/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2020/03/17/book-review-hoover/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2020/04/06/sscjc-real-world-depression-measurement/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2020/04/08/2019-predictions-calibration-results/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2020/04/29/predictions-for-2020/
- https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2020/06/07/take-the-new-nootropics-survey/

**Comment by benide** [comment]
Weird, I'll try to fix it up a bit more later today :-)

**Comment by georgjaehnig** [comment]
Yup, maybe run a `wget` on all your URLs first and check how many come back with 404.

**Comment by eggsyntax** [comment]
Thanks to both of you for working on this!

I think the failure is probably because those all point to the same capture (20200618....) and the wayback machine presumably didn't capture all pages on SSC at the same time. That's a guess, but it seems likely.

Actually I'm not sure how this worked in the first place using the definitions in the repo -- the 2019 and 2020 definitions point to archive.org links, but the 2013-2018 definitions point directly to SSC. I noticed that because I was thinking it might be easier to combine all of @georgjaehnig 's year-by-year files rather than @benide 's approach of generating links from the archive page, on the assumption that the year-by-year files presumably all work. 

Interestingly, I checked one of the ones that you listed as failing (the [first one](https://web.archive.org/web/20200618075053/https://slatestarcodex.com/2016/08/25/devoodooifying-psychology/)) and it does show up in the epub, so I'm not sure what's going on unless you originally captured the 2013-2018 pages before SSC went down?

**Comment by georgjaehnig** [comment]
@eggsyntax I've created the first EPUBs in 2017, and then in mid-2019 when SSC was still up.

Now, because of #9, I've recreated 2019 and added 2020 – with links from archive.org, since now SSC is down.

So adding links from the 2013-2018 definitions won't help, since they're not accessible on SSC right now.

**Comment by eggsyntax** [comment]
Just did a bit of digging into [the various APIs](https://archive.org/help/wayback_api.php) that web.archive.org supports. I was really hoping there'd be something like:

https://web.archive.org/web/latest/https://slatestarcodex.com/2016/08/25/devoodooifying-psychology/

to retrieve the most recently stored version, but if there is, I haven't been able to find it. There's a consolation prize, though:

Return a plaintext list of captures:
https://web.archive.org/web/timemap/http://slatestarcodex.com/2016/08/25/devoodooifying-psychology/

Results are in this format, with the date of the capture (ie the date that can be substituted into the final URL) as the second (space-separated) field.
`com,slatestarcodex)/2016/08/25/devoodooifying-psychology 20200624122713 https://slatestarcodex.com/2016/08/25/devoodooifying-psychology/ text/html 404 T3AQJDGWC4JGRJHRQHERX5JZGG76K5BO - - 764 3008132448 archiveteam_archivebot_go_20200624150002/old.reddit.com-inf-20200623-164549-7ljnn-00022.warc.gz`

The last line (the one I pasted above) is the most recent capture, and the direct URL of that latest capture is
https://web.archive.org/web/20200624122713/http://slatestarcodex.com/2016/08/25/devoodooifying-psychology/

The trouble is that that date is from just a few days ago, after the site had been taken down, so it returns a 404 page :/ . This would have meant that my imagined `https://web.archive.org/web/latest/...` wouldn't have worked even if it did exist.

What would presumably work better would be to get the *first* version, at the cost of missing any later edits, or to get the last version before the takedown, at the cost of additional parsing & date comparison.

There's also an equivalent URL for grabbing the same info in JSON instead of plaintext.

My JS chops are pretty rusty, and I'm really short on time at the moment, but hopefully this info can get someone at least a bit closer.

**Comment by georgjaehnig** [comment]
Thinking out of the box: A different approach could be to simply use the generated by-year EPUBs, and merge them into one big file. I am no EPUB expert though, but if someone is, this should be a safe (and easy?) way.

**Comment by eggsyntax** [comment]
I'm definitely not especially knowledgeable about epubs.

That said, I think I may be able to find time tonight to throw together a script to use the list of URLs that Ben grabbed to pull the timemaps from the archive and build a valid archive.org URL for each. If I can find time to do it I'll just run it locally and hand over a list of the valid URLs.

**Comment by georgjaehnig** [comment]
Sounds great. Crossing fingers. :)

> and hand over a list of the valid URLs.

You can also try running this webpages-to-ebook script. It only needs a clone, `npm i`, and then

    $ node index.js definitions/slatestarcodex.base.yml your-definition-file.yml

**Comment by benide** [comment]
Glad to see you all are getting somewhere! I'll let you all take that route, I'm going to write a script that grabs the url of working archive links using some of what was mentioned above :)

**Comment by benide** [comment]
Ok, so, here's what I've come up with that is hopefully reusable. It ain't pretty, but I've learned some random command line things along the way, so I'm happy with it haha:
```bash
echo "shortname: ssc_archive
metadata:
  dc:
    title: SSC Archive
tags:
  title: h2
content:" > ssc.yml

curl -s https://web.archive.org/web/20200618075053/https://slatestarcodex.com/archives/ | \
grep sya_container | \
grep -oP '(https://slatestarcodex.com/[\d]{4}/[\d]{2}/[\d]{2}/[^"]++)(?=")' | \
grep -vP '(/open-thread)|(/ot)|(meetup)|(classified)|(links)' | \
tac | uniq | \
xargs -n1 -I % sh -c "curl -s https://web.archive.org/web/timemap/% | awk -F' ' '{ print \$2 }' | tac | awk 'BEGIN {A=20200620000000} {if (\$0<A) {print \"https://web.archive.org/web/\" \$0 \"/%\"; A=0}}'" | \
awk -F '/' 'BEGIN {A=""} { if ($9!=A) {print "- raw: \"<h1>" $9 "</h1>\""; A=$9}; print "- " $0 }' >> ssc.yml
```

In theory, this will give the latest working links for everything, and the resulting file should be immediately usable with @georgjaehnig's script. It has to query archive.org for every single post, so it's taking a bit to generate the yml file...

**Comment by benide** [comment]
Updated, [same gist as before](https://gist.github.com/benide/a3c159f2fa541e8a040910dcd84af34b). I'll give it a try my self and let you know.

**Comment by eggsyntax** [comment]
Ha! I took a **much** longer-winded approach and put together a [fairly verbose Clojure script](https://gist.github.com/eggsyntax/521d99af8b609047cf8cd447c7f64eaa). My bash-fu isn't that good as yet.

Mine'll be running for a while, though; I kept getting rate-limited, so now I've slowed it way down.

**Comment by benide** [comment]
That happened to me too, found I could do 100 API calls very quickly and then it was unhappy... Eventually got it, 100 at a time haha.

edit: Wow, Clojure makes me feel very at home. I use Emacs, and this just looks like elisp. I guess I need to start playing with some different lisps.

**Comment by eggsyntax** [comment]
Looks like our results were nearly identical (there were some small differences; eg the first couple of lines were in different orders; I didn't include the year headers [in mine](https://gist.github.com/eggsyntax/197c28c7584f243d552fd75571e48dd5)).

Clojure's an enormous pleasure, by far my favorite language and has been for about 5 years so far (out of 6-10 langs that I know fairly well). It combines all the inherent lispy goodness with a really sensible take on functional programming (it nudges you away from mutable state and toward pure functions wherever that's reasonable, but won't stand in your way when you're doing something small or one-off and just want to hack in place on a bunch of global vars). And it just has a tremendous amount of coherence in the design; you can tell the author spent years thinking really hard about this and implementing prototypes before settling on a design where everything clicks nicely with everything else. If you're curious about it but not necessarily committed to diving in whole-hog, one of the nicest places to start is with a couple of Rich Hickey's talks. I generally like talks less than I like reading, and less than I like learning by experimentation, but his talks are a dramatic exception; the ideas he expresses in them really transformed the way I think about programming. The two I'd recommend most would be [Are We There Yet?](https://www.infoq.com/presentations/Are-We-There-Yet-Rich-Hickey/) and [Simple Made Easy](https://www.infoq.com/presentations/Simple-Made-Easy/).

**Comment by benide** [comment]
In the latest bash I put above, I was more careful to not reorder posts. It only matters for things posted on the same day, and probably doesn't *really* matter at all. You have more posts than me because I've filtered a few things out, which is coming from this part:
```bash
grep -vP '(/open-thread)|(/ot)|(meetup)|(classified)|(links)'
```
There are still things that aren't really necessary left over (like posts asking people to take yearly surveys), but no easy way to remove them without doing it entirely by hand.

I'll check Clojure out for sure, thanks for the links!

@georgjaehnig: I tried running
```
$ node index.js definitions/slatestarcodex.base.yml ssc-archive.yml
```
Everything downloaded happily. A few things got skipped from not parsing correctly, not sure why. It eventually said "Done", but I can't find the epub anywhere. In particular, it isn't in `output/epub`.

**Comment by georgjaehnig** [comment]
@benide 

> Everything downloaded happily. A few things got skipped from not parsing correctly, not sure why.

Oh, I guess this is because they **didn't** download correctly but got a 404 instead – which my script is not catching properly. I'll look at this now.
 

> It eventually said "Done", but I can't find the epub anywhere. In particular, it isn't in output/epub.

Oh, this is weird. Don't know what happened. Can you try to isolate the bug and e.g. run a dummy definition with only 2 (working) URLs or so?

**Comment by georgjaehnig** [comment]
> Everything downloaded happily.

So I've fixed the download error reporting now, if `wget` doesn't exit with `0`, a problem is reported to the console.

**Comment by benide** [comment]
I'll come back to this tomorrow :+1:

**Comment by georgjaehnig** [comment]
Take a look: A nice person who wants to stay anonymous, generated an all-article epub (and mobi):
https://drive.google.com/drive/folders/10q-YfudWvfs5vF3HCMW-dEiQjn4x2TlK?usp=sharing

Is it it good? Then we could share it.

**Comment by benide** [comment]
Seems to have images, good bookmarks, etc. Definitely worth sharing!

**Comment by eggsyntax** [comment]
We've been scooped! It looks terrific, they did a really nice job on it.

The epub (viewing in ibooks on mac since that's the machine I'm on) tried to make web connections to SSC and to archive.org without me clicking on anything (unless it was a misclick, which is conceivable), but maybe it's just lazily fetching an image or two? No clue, I didn't realize they could even do that without a user action.

Woohoo, I can rest easy knowing I have it all at my fingertips in one big volume :) 

Thanks, y'all!

**Comment by georgjaehnig** [comment]
Great, I've put it here: https://www.reddit.com/r/slatestarcodex/comments/hkbfj4/all_articles_20132020_in_one_ebook_epub_mobi_pdf/
