### ISSUE TITLE
Just a big thanks for this project

### ISSUE THREAD

**Issue by m040601** [georgjaehnig/webpages-to-ebook#15]
First of all, a big thanks for this project.
It's rare to see something cooked up with the simplicity, clareness and usefulness. that you came up with.

Making use of the "right tool for the job" like Pandoc or wget, instead of reinventing the wheell with even more new npm modules.

A very big upvote that you made your project some how to be "portable" and not force or make any "node/npm" package installation mess in the users computer.
This is especially important for users who value a clean and not bloated system, controlled by their package manager.

By choosing, 
cd webpages-to-ebook
npm install.

And not recommending any "npm install -g XYZ" , or even worse "sudo npm ..."
This makes it extremelly attractive and usefull for users who are not iespecially interested in node/npm and choose not to have to cope or be forced with the mess of npm packages installation and updates.

It's a pitty your project isn't better known.

I'd like to suggest you to update your README.md page.
You should move tihis part to the very top of the page,

> git clone ..
> cd web..
> node install ..

And stress the fact that your project is self-contained. It doesnt create any "global mess" of npm packages on your system. Maybe also put an example with a recipe for collecting things from different generic sites, like bbc.com or nyt.com. A very simple example of a YAML recipe, not a link to it.

The first time I saw it some months ago, I didnt pay much attention because
you have the (too) many "slatestarcodex" recipes listed very prominently at the top.
I thought, hmm, maybe some guy did a site specific scraper for one or two sites he likes. I'm not going to mess with npm packages just to ttest it.

**Comment by georgjaehnig** [comment]
Thanks for your compliment!

I've moved now the Usage in the README to the start.
