### ISSUE TITLE
Table Of Contents?

### ISSUE THREAD

**Issue by adamgordonbell** [georgjaehnig/webpages-to-ebook#16]
Great project. Is there a way to control the TOC that is generated. It is including every heading in each article and I would rather it just include the articles themselves.

**Comment by adamgordonbell** [comment]
I figured it out. pandoc has a depth option:
```
'--toc-depth', '2',
```

**Comment by georgjaehnig** [comment]
Great that you could solve it yourself. I was travelling. :)
