### ISSUE TITLE
TypeError: Cannot read property 'toString' of undefined (data.toString())

### ISSUE THREAD

**Issue by tandriamil** [georgjaehnig/webpages-to-ebook#6]
Hi,

I have an error when trying to execute on `definitions/markmanson.yml`:

```
node index.js definitions/markmanson.yml

[A lot of logs saying processing/downloading]

[hidden_path]/webpages-to-ebook/index.js:62
    let html = data.toString();
                    ^

TypeError: Cannot read property 'toString' of undefined
    at ReadFileContext.fs.readFile [as callback] ([hidden_path]/webpages-to-ebook/index.js:62:21)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:352:13)
```

Thank you.

**Comment by georgjaehnig** [comment]
Thanks for reporting. I could not reproduce it though. Just called 

    node index.js definitions/markmanson.yml

and it ran successfully.

What Node.js version do you use? Mine is v10.6.0.

**Comment by tandriamil** [comment]
I'm using v10.3.0 but I looked at it again and found the error. Thought that I had wget per default but don't. After installing every dependencies, everything worked fine!

Sorry for the mistake and thanks for your help and for this nice tool!

Have a nice day.

**Comment by tandriamil** [comment]
Btw, maybe displaying a custom error message when the system dependencies (wget / pandoc) are not detected, or when the content cannot be processed, could help people (like me) in the case they did not really read the readme (shame, shame, shame...)?

**Comment by georgjaehnig** [comment]
Good idea, added issue #7.
