### ISSUE TITLE
Filter out hidden open threads?

### ISSUE THREAD

**Issue by wyattscarpenter** [georgjaehnig/webpages-to-ebook#8]
The non-integer open threads do not actually contain any content, yet they appear in the example epubs.

**Comment by georgjaehnig** [comment]
Thanks for your report! Can you please specify a bit more? Which epub / definition file, and which URL for example?

**Comment by wyattscarpenter** [comment]
Ah, yes, sorry for not being more specific: I was looking through slatestarcodex.year.2017.epub, and I noticed that it has a bunch of almost-blank pages where the hidden open threads would be, like https://slatestarcodex.com/2017/01/08/open-thread-66-5/?comments=false
 and https://slatestarcodex.com/2017/01/11/open-thread-66-75/?comments=false

![image](https://user-images.githubusercontent.com/27367056/53293150-09c36a80-3794-11e9-8c67-199a20acce89.png)

I assume this would also be the case in slatestarcodex.year.2016.epub, because the hidden open threads started in 2016, based on the listing on https://slatestarcodex.com/archives/

**Comment by georgjaehnig** [comment]
Hi @wyattscarpenter, thanks for you elaboration! I thought about this but think I better leave it as is. The "pain" of these Open Threads seems bearable but trying to filter them out could

- lead to false positives, then an article would be missing.
- sometimes Scott refers to an OT, then it's good to see in the ebook when they were and what their intro was.

**Comment by wyattscarpenter** [comment]
I don't think the second point would really be an issue because the hidden open threads (as distinct from the regular open threads) all start with the same intro and AFAIK are never referenced by Scott (I don't think he even reads them). But, you've made a reasonable decision on the whole. Thanks for your time!
