### ISSUE TITLE
June 2020 update?

### ISSUE THREAD

**Issue by JeremyNguyenPhD** [georgjaehnig/webpages-to-ebook#9]
I wonder if there's any chance you'd be able to update the compiled epubs to June 2020, using, say:
https://web.archive.org/web/*/www.slatestarcodex.com

**Comment by georgjaehnig** [comment]
Good idea. I'm working on it.

**Comment by JeremyNguyenPhD** [comment]
Thank you so much.

**Comment by georgjaehnig** [comment]
OK, done!

Also published the link here:
https://www.reddit.com/r/slatestarcodex/comments/hfj0kr/all_ssc_articles_as_epub_grouped_by_year_updated/
https://twitter.com/jorges/status/1276082690001944577

**Comment by JeremyNguyenPhD** [comment]
Wow, this is amazing. Thank you again.
